#include "resources.h"

QString Resources::SOUND_FILE_DRAG_IMG_PATH = "../../resources/images/dick.png";
QString Resources::DATABASE_PATH = "../../db/dsamediacontrolkit.db";
QString Resources::ICON_PLAY_PATH = "../../resources/images/icon_play.png";
QString Resources::ICON_PAUSE_PATH = "../../resources/images/icon_pause.png";
QString Resources::ICON_STOP_PATH = "../../resources/images/icon_stop.png";
QString Resources::DARK_STYLE = "QMainWindow {"
                                "   background-color: #373738;"
                                "}"
                                ""
                                "QMenuBar {"
                                "   background-color: #545556;"
                                "}"
                                ""
                                "QMenuBar::item {"
                                "   background : transparent;"
                                "   color : white;"
                                "}"
                                ""
                                "QMenuBar::item:selected {"
                                "   background : #198e09;"
                                "}"
                                ""
                                "QGroupBox {"
                                "   border: 1px solid gray;"
                                "   background-color: #373738;"
                                "}"
                                ""
                                "QTreeView {"
                                "   background-color : #545556;"
                                "   color : white;"
                                "   margin-bottom : 5px;"
                                "}"
                                ""
                                "QTreeView::item {"
                                "   margin : 3px;"
                                "}"
                                ""
                                ""
                                "QHeaderView::section {"
                                "   background-color : #373738;"
                                "   color : white;"
                                "   border : none;"
                                "   padding : 5px;"
                                "}"
                                ""
                                "QListView {"
                                "   background-color : #545556;"
                                "   color : white;"
                                "   margin-top : 5px;"
                                "}"
                                ""
                                "QListView::item {"
                                "   margin : 3px;"
                                "}"
                                ""
                                "QGraphicsView {"
                                "   background-color : #545556;"
                                "}"
                                ""
                                "QSplitter::handle {"
                                "   height : 5px;"
                                "   background-color : #373738;"
                                "}";
